video: Fix build error with global inclusion of videomodes
The following commit:

commit de701d118380de12a48c8a4fb345e9f909329432
Author: Syed Mohammed Khasim <khasim@ti.com>
Date:   Tue Apr 19 14:00:34 2011 -0500

   OMAP3: Add DSS driver for OMAP3

Added videomodes to the object list w/o any protection.  This causes
build issues like:

videomodes.o:(.rodata.res_mode_init+0x0): multiple definition of `res_mode_init'
videomodes.o:(.rodata.res_mode_init+0x0): first defined here
videomodes.o: In function `video_get_params':
/local/home/galak/git/u-boot/drivers/video/videomodes.c:160: multiple definition of `video_get_params'
videomodes.o:/local/home/galak/git/u-boot/drivers/video/videomodes.c:160: first defined here
videomodes.o: In function `video_get_video_mode':
/local/home/galak/git/u-boot/drivers/video/videomodes.c:229: multiple definition of `video_get_video_mode'
videomodes.o:/local/home/galak/git/u-boot/drivers/video/videomodes.c:229: first defined here
videomodes.o:(.rodata.vesa_modes+0x0): multiple definition of `vesa_modes'
videomodes.o:(.rodata.vesa_modes+0x0): first defined here
make[1]: *** [libvideo.o] Error 1

Remove the unconditional inclusion and move to adding to
CONFIG_VIDEO_OMAP3 case.

Signed-off-by: Kumar Gala <galak@kernel.crashing.org>